package com.acme.orders;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A Lombok @Data entity: getId/setStatus/equals/the constructors are all
 * generated by the annotation processor and exist in NO source line. Analysis
 * runs on the original text (--delombok-mode types-only, §5.3), so calls to
 * them can never bind to a method — the honest reason is `lombok-generated`.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Order {

    String id;

    String status;
}
