"""Wadi data contracts — the single source of truth (architecture.md §7)."""

from wadi_contracts.base import ArtifactEnvelope, SnapshotEnvelope, WadiModel
from wadi_contracts.boundary import (
    KNOWN_CLIENT_LIBRARIES,
    MODELLED_CLIENT_LIBRARIES,
    AnalysisCoverage,
    GatewayRoute,
    NetworkIdentity,
    ServiceBoundary,
)
from wadi_contracts.comms import MqInteraction, RemoteCall
from wadi_contracts.datamodel import DataModel, DataModelField, DataModelRelation
from wadi_contracts.endpoint import (
    AuthEvidence,
    AuthEvidenceKind,
    Endpoint,
    EndpointAuth,
    EndpointParam,
    FieldShape,
    ParamLocation,
    ShapeKind,
    TypeShape,
)
from wadi_contracts.enums import (
    Confidence,
    HttpMethod,
    IcfgEdgeKind,
    IcfgNodeKind,
    JobStatus,
    JobType,
    MqDirection,
    Provenance,
    ServiceKind,
    SinkKind,
    SnapshotStatus,
    SourceVariant,
    TargetKind,
    TriggerKind,
)
from wadi_contracts.export import ExportManifest
from wadi_contracts.icfg import (
    BranchCondition,
    Icfg,
    IcfgEdge,
    IcfgNode,
    MethodInfo,
    MethodParam,
    OperandOrigin,
    OperandRef,
)
from wadi_contracts.ids import (
    data_model_id,
    endpoint_id,
    method_id,
    mq_interaction_id,
    normalize_repo_source,
    placeholder_service_id,
    remote_call_id,
    remote_edge_id,
    service_id,
    simplify_uri,
)
from wadi_contracts.jobs import ExtractionJob, JobClaim
from wadi_contracts.registry import CONTRACT_MODELS
from wadi_contracts.source import MethodRef, SourceAnchor
from wadi_contracts.stitching import (
    AnalysisCoverageSection,
    CoverageReport,
    CoverageTotals,
    ExternalApiEntry,
    PlaceholderEntry,
    ServiceCoverageEntry,
    StitchedEdge,
    UnmodelledMechanismEntry,
    UnresolvedCallEntry,
    edge_target_key,
)
from wadi_contracts.system import RepoSource, Snapshot, System
from wadi_contracts.tags import (
    TAG_REGISTRY_VERSION,
    Tag,
    TagValidationError,
    parse_tag,
    registered_namespaces,
    validate_tag,
)
from wadi_contracts.timeutil import UtcDatetime, ensure_utc, utc_now
from wadi_contracts.version import SCHEMA_VERSION
from wadi_contracts.views import RemoteEdgeItem, RemoteEdgesView, ServiceSummary, SourceView

__all__ = [
    "CONTRACT_MODELS",
    "KNOWN_CLIENT_LIBRARIES",
    "MODELLED_CLIENT_LIBRARIES",
    "SCHEMA_VERSION",
    "TAG_REGISTRY_VERSION",
    "AnalysisCoverage",
    "AnalysisCoverageSection",
    "ArtifactEnvelope",
    "AuthEvidence",
    "AuthEvidenceKind",
    "BranchCondition",
    "Confidence",
    "CoverageReport",
    "CoverageTotals",
    "DataModel",
    "DataModelField",
    "DataModelRelation",
    "Endpoint",
    "EndpointAuth",
    "EndpointParam",
    "ExportManifest",
    "ExternalApiEntry",
    "ExtractionJob",
    "FieldShape",
    "GatewayRoute",
    "HttpMethod",
    "Icfg",
    "IcfgEdge",
    "IcfgEdgeKind",
    "IcfgNode",
    "IcfgNodeKind",
    "JobClaim",
    "JobStatus",
    "JobType",
    "MethodInfo",
    "MethodParam",
    "MethodRef",
    "MqDirection",
    "MqInteraction",
    "NetworkIdentity",
    "OperandOrigin",
    "OperandRef",
    "ParamLocation",
    "PlaceholderEntry",
    "Provenance",
    "RemoteCall",
    "RemoteEdgeItem",
    "RemoteEdgesView",
    "RepoSource",
    "ServiceBoundary",
    "ServiceCoverageEntry",
    "ServiceKind",
    "ServiceSummary",
    "ShapeKind",
    "SinkKind",
    "Snapshot",
    "SnapshotEnvelope",
    "SnapshotStatus",
    "SourceAnchor",
    "SourceVariant",
    "SourceView",
    "StitchedEdge",
    "System",
    "Tag",
    "TagValidationError",
    "TargetKind",
    "TriggerKind",
    "TypeShape",
    "UnmodelledMechanismEntry",
    "UnresolvedCallEntry",
    "UtcDatetime",
    "WadiModel",
    "data_model_id",
    "edge_target_key",
    "endpoint_id",
    "ensure_utc",
    "method_id",
    "mq_interaction_id",
    "normalize_repo_source",
    "parse_tag",
    "placeholder_service_id",
    "registered_namespaces",
    "remote_call_id",
    "remote_edge_id",
    "service_id",
    "simplify_uri",
    "utc_now",
    "validate_tag",
]
